[package]
name = "alc"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
array2d = "0.3.2"
delegate = "0.12.0"
rand = "0.8.5"
regex = "1.10.4"
serde = "1.0.198"
strum = "0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.58"
tqdm = "0.7.0"
