[keycode_options]
include_alphas = true
include_numbers = false
include_number_symbols = false
include_brackets = false
include_misc_symbols = true
include_misc_symbols_shifted = true
explicit_inclusions = ["_SPC", "_SFT", "_ENT", "_AMPR"]